services:
  wordpress-test:
    build:
      context: ../..
      dockerfile: docker/unit-tests/Dockerfile
    volumes:
      - ../../searchpixel:/opt/wordpress/wp-content/plugins/searchpixel
      - ../../tests:/opt/tests/plugins/searchpixel/tests
      - ./phpunit.xml:/opt/tests/phpunit.xml
      - ./autoload.php:/opt/tests/autoload.php
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    networks:
      - wordpress

  mariadb:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h127.0.0.1 -u\"$${MYSQL_USER}\" -p\"$${MYSQL_PASSWORD}\" --silent" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    networks:
      - wordpress

volumes:
  db_data:

networks:
  wordpress:
