services:
  api:
    build:
      context: ../dummy-api
      dockerfile: ../dummy-api/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - wordpress

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../thinkpixel-search-rag:/opt/wordpress/wp-content/plugins/thinkpixel-search-rag
    depends_on:
      - mariadb
      - api
    ports:
      - "8081:80"
    networks:
      - wordpress

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    networks:
      - wordpress

volumes:
  db_data:


networks:
  wordpress:
